version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/app/app
    networks:
      - enrollment-network

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - enrollment-network

  nginx:
    image: nginx:1.25
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./app/static:/app/app/static
    depends_on:
      - web
    networks:
      - enrollment-network

networks:
  enrollment-network:
    driver: bridge

volumes:
  postgres_data: