"""Add avatar and bio fields to User model

Revision ID: 726221331ae8
Revises: 3cfb3ea12959
Create Date: 2025-03-02 05:01:37.211066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726221331ae8'
down_revision = '3cfb3ea12959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.TEXT(), nullable=True))
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
